In [1]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline
from tqdm import tqdm
from warnings import filterwarnings
from tensorflow import keras
import tensorflow as tf
from matplotlib import pyplot
filterwarnings('ignore')
from silence_tensorflow import silence_tensorflow
silence_tensorflow()

In [2]:
import os
print(os.getcwd())

c:\lab\LDL\cap


In [3]:
# csv, model LOAD
df_scaler=pd.read_csv("./new_data.csv")
df_scaler=df_scaler.drop([df_scaler.columns[0]], axis=1)

"""model_1 = tf.keras.models.load_model('DNN_LDL_4categorical.h5')
model_2= tf.keras.models.load_model('DNN_HDL_4categorical.h5')
model_3= tf.keras.models.load_model('DNN_TG_4categorical.h5')
model_4= tf.keras.models.load_model('DNN_TC_4categorical.h5')
model_5= tf.keras.models.load_model('DNN_LDL_4categorical(model_5)_forprediction_HDL.h5')
model_6= tf.keras.models.load_model('DNN_LDL_4categorical(model_6)_forprediction_TG.h5')
model_7= tf.keras.models.load_model('DNN_LDL_4categorical(model_7)_forprediction_TC.h5')
model_8= tf.keras.models.load_model('DNN_LDL_4categorical(model_8)_forprediction_LDL.h5')"""

"model_1 = tf.keras.models.load_model('DNN_LDL_4categorical.h5')\nmodel_2= tf.keras.models.load_model('DNN_HDL_4categorical.h5')\nmodel_3= tf.keras.models.load_model('DNN_TG_4categorical.h5')\nmodel_4= tf.keras.models.load_model('DNN_TC_4categorical.h5')\nmodel_5= tf.keras.models.load_model('DNN_LDL_4categorical(model_5)_forprediction_HDL.h5')\nmodel_6= tf.keras.models.load_model('DNN_LDL_4categorical(model_6)_forprediction_TG.h5')\nmodel_7= tf.keras.models.load_model('DNN_LDL_4categorical(model_7)_forprediction_TC.h5')\nmodel_8= tf.keras.models.load_model('DNN_LDL_4categorical(model_8)_forprediction_LDL.h5')"

In [4]:
id_1="LDL"
id_2="HDL"
id_3="TG"
id_4="TC"

In [6]:
# 정확도 배열
accuracy_list=[0 for i in range(8)]

# 클래스 개수 배열
class_list=[[0]*4 for i in range(8)]

#각 특징별 x,y 생성
X_onlybody=df_scaler.drop(['LDL', 'HDL', 'TG', 'TC'], axis=1) #신체계측치로만 구성
X_onlybody=np.array(X_onlybody)

Y_model_1=np.array(df_scaler[id_1])
Y_model_1=np.array(Y_model_1)

Y_model_2=np.array(df_scaler[id_2])
Y_model_2=np.array(Y_model_2)

Y_model_3=np.array(df_scaler[id_3])
Y_model_3=np.array(Y_model_3)

Y_model_4=np.array(df_scaler[id_4])
Y_model_4=np.array(Y_model_4)

# <신체계측치를 이용해 예측한 model_1 특징 수치>

In [21]:
#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_onlybody, Y_model_1, train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_1 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_1.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_1.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_1.save('DNN_LDL_4categorical.h5')

accuracy_list[0]=round((model_1.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_1=model_1.predict(X_onlybody)

predict_model_1_list=[]
for li in predict_model_1:
    index=li.argmax()
    predict_model_1_list.append(index)

for i in range(4):
    class_list[0][i]=predict_model_1_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 3ms/step - loss: 2.6520 - accuracy: 0.4600
Epoch 2/150
38/38 [==============================] - 0s 3ms/step - loss: 1.7229 - accuracy: 0.4467
Epoch 3/150
38/38 [==============================] - 0s 3ms/step - loss: 1.3571 - accuracy: 0.4833
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.2407 - accuracy: 0.4967
Epoch 5/150
38/38 [==============================] - 0s 3ms/step - loss: 1.1567 - accuracy: 0.4400
Epoch 6/150
38/38 [==============================] - 0s 3ms/step - loss: 1.0643 - accuracy: 0.4867
Epoch 7/150
38/38 [==============================] - 0s 3ms/step - loss: 1.0493 - accuracy: 0.4633
Epoch 8/150
38/38 [==============================] - 0s 3ms/step - loss: 1.0067 - accuracy: 0.5033
Epoch 9/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9573 - accuracy: 0.5033
Epoch 10/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9589 - accuracy: 0.5167
Epoch 11/

# <신체계측치를 이용해 예측한 model_2 특징 수치>

In [22]:
#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_onlybody, Y_model_2, train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_2 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_2.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_2.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_2.save('DNN_HDL_4categorical.h5')


accuracy_list[1]=round((model_2.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_2=model_2.predict(X_onlybody)

predict_model_2_list=[]
for li in predict_model_2:
    index=li.argmax()
    predict_model_2_list.append(index)

for i in range(4):
    class_list[1][i]=predict_model_2_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 5ms/step - loss: 5.1236 - accuracy: 0.4800
Epoch 2/150
38/38 [==============================] - 0s 7ms/step - loss: 2.9017 - accuracy: 0.4600
Epoch 3/150
38/38 [==============================] - 0s 4ms/step - loss: 1.9082 - accuracy: 0.4900
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.7469 - accuracy: 0.5067
Epoch 5/150
38/38 [==============================] - 0s 3ms/step - loss: 1.4426 - accuracy: 0.5233
Epoch 6/150
38/38 [==============================] - 0s 3ms/step - loss: 1.2928 - accuracy: 0.4967
Epoch 7/150
38/38 [==============================] - 0s 3ms/step - loss: 1.2421 - accuracy: 0.4767
Epoch 8/150
38/38 [==============================] - 0s 2ms/step - loss: 1.1359 - accuracy: 0.4667
Epoch 9/150
38/38 [==============================] - 0s 2ms/step - loss: 1.0952 - accuracy: 0.4600
Epoch 10/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9988 - accuracy: 0.5133
Epoch 11/

# <신체계측치를 이용해 예측한 model_3 특징 수치>

In [23]:
#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_onlybody, Y_model_3, train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_3 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_3.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_3.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_3.save('DNN_TG_4categorical.h5')


accuracy_list[2]=round((model_3.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_3=model_3.predict(X_onlybody)

predict_model_3_list=[]
for li in predict_model_3:
    index=li.argmax()
    predict_model_3_list.append(index)

for i in range(4):
    class_list[2][i]=predict_model_3_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 3ms/step - loss: 4.0118 - accuracy: 0.6100
Epoch 2/150
38/38 [==============================] - 0s 3ms/step - loss: 1.4942 - accuracy: 0.6267
Epoch 3/150
38/38 [==============================] - 0s 2ms/step - loss: 1.0602 - accuracy: 0.6967
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9359 - accuracy: 0.7333
Epoch 5/150
38/38 [==============================] - 0s 5ms/step - loss: 0.8987 - accuracy: 0.7467
Epoch 6/150
38/38 [==============================] - 0s 5ms/step - loss: 0.7828 - accuracy: 0.7667
Epoch 7/150
38/38 [==============================] - 0s 5ms/step - loss: 0.7257 - accuracy: 0.7900
Epoch 8/150
38/38 [==============================] - 0s 3ms/step - loss: 0.7348 - accuracy: 0.7900
Epoch 9/150
38/38 [==============================] - 0s 3ms/step - loss: 0.7232 - accuracy: 0.7767
Epoch 10/150
38/38 [==============================] - 0s 4ms/step - loss: 0.7233 - accuracy: 0.7967
Epoch 11/

# <신체계측치를 이용해 예측한 model_4 특징 수치>

In [24]:
#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_onlybody, Y_model_4, train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_4 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_4.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_4.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_4.save('DNN_TC_4categorical.h5')


accuracy_list[3]=round((model_4.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_4=model_4.predict(X_onlybody)

predict_model_4_list=[]
for li in predict_model_4:
    index=li.argmax()
    predict_model_4_list.append(index)

for i in range(4):
    class_list[3][i]=predict_model_4_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 4ms/step - loss: 6.4097 - accuracy: 0.4700
Epoch 2/150
38/38 [==============================] - 0s 4ms/step - loss: 3.5361 - accuracy: 0.4367
Epoch 3/150
38/38 [==============================] - 0s 3ms/step - loss: 2.5125 - accuracy: 0.4367
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.4961 - accuracy: 0.4800
Epoch 5/150
38/38 [==============================] - 0s 3ms/step - loss: 1.5081 - accuracy: 0.4800
Epoch 6/150
38/38 [==============================] - 0s 3ms/step - loss: 1.2869 - accuracy: 0.5100
Epoch 7/150
38/38 [==============================] - 0s 4ms/step - loss: 1.2211 - accuracy: 0.5367
Epoch 8/150
38/38 [==============================] - 0s 5ms/step - loss: 1.1008 - accuracy: 0.5367
Epoch 9/150
38/38 [==============================] - 0s 4ms/step - loss: 1.0931 - accuracy: 0.5367
Epoch 10/150
38/38 [==============================] - 0s 4ms/step - loss: 1.1164 - accuracy: 0.5133
Epoch 11/

# ====test-신체+일반 prediction====

In [14]:
predict_model_2_list=np.array(predict_model_2_list, dtype='float64')
predict_model_2_list=predict_model_2_list.reshape(-1,1)

predict_model_3_list=np.array(predict_model_3_list, dtype='float64')
predict_model_3_list=predict_model_3_list.reshape(-1,1)

predict_model_4_list=np.array(predict_model_4_list, dtype='float64')
predict_model_4_list=predict_model_4_list.reshape(-1,1)

X_model_prediction=np.hstack([X_onlybody, predict_model_2_list, predict_model_3_list, predict_model_4_list])

In [15]:
#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_model_prediction,Y_model_1,train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

In [ ]:
# DNN_prediction 모델 
accuracy_pre=0
while accuracy_pre<=0.67:
    DNN_prediction = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=4, activation='softmax')
    ])

    DNN_prediction.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

    DNN_prediction.fit(x_train, y_train_encoded, epochs=150, batch_size=8, verbose=0)

    accuracy_pre=round(DNN_prediction.evaluate(x_test, y_test_encoded)[1],4)
    
print("Accuracy: %.4f" % (DNN_prediction.evaluate(x_test, y_test_encoded)[1]))

In [17]:
DNN_prediction.save('DNN_normal_prediction.h5')

# ====정답 수치 넣어서 prediction====

In [18]:
X_all_real=df_scaler.drop(['LDL'], axis=1) #신체계측치+실제 HDL, TG, TC

#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_all_real,Y_model_1,train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

In [19]:
# DNN_prediction 모델 
accuracy_real=0
while accuracy_real<=0.78:
    DNN_real = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=4, activation='softmax')
    ])

    DNN_real.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

    DNN_real.fit(x_train, y_train_encoded, epochs=150, batch_size=8, verbose=0)

    accuracy_real=round(DNN_real.evaluate(x_test, y_test_encoded)[1],4)
    
print("Accuracy: %.4f" % (DNN_real.evaluate(x_test, y_test_encoded)[1]))

3/3 [==============================] - 0s 2ms/step - loss: 3.3733 - accuracy: 0.8022
Accuracy: 0.8022


In [20]:
DNN_real.save('DNN_real_prediction.h5')

# <신체 + model_1 예측값 -> model_5(id_2 수치)로 예측>

In [27]:
#예측값 붙여주기
#X_model_5 = X_onlybody+model_1_prediction
predict_model_1_list=np.array(predict_model_1_list, dtype='float64')
predict_model_1_list=predict_model_1_list.reshape(-1,1)
X_model_5=np.hstack([X_onlybody, predict_model_1_list])

#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_model_5,Y_model_2,train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_5 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_5.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_5.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_5.save('DNN_LDL_4categorical(model_5)_forprediction_HDL.h5')

accuracy_list[4]=round((model_5.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_5=model_5.predict(X_model_5)

predict_model_5_list=[]
for li in predict_model_5:
    index=li.argmax()
    predict_model_5_list.append(index)

for i in range(4):
    class_list[4][i]=predict_model_5_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 3ms/step - loss: 4.9210 - accuracy: 0.4333
Epoch 2/150
38/38 [==============================] - 0s 3ms/step - loss: 2.4258 - accuracy: 0.4967
Epoch 3/150
38/38 [==============================] - 0s 3ms/step - loss: 1.9844 - accuracy: 0.4233
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.4881 - accuracy: 0.4500
Epoch 5/150
38/38 [==============================] - 0s 2ms/step - loss: 1.2602 - accuracy: 0.4600
Epoch 6/150
38/38 [==============================] - 0s 4ms/step - loss: 1.1066 - accuracy: 0.4933
Epoch 7/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9936 - accuracy: 0.5433
Epoch 8/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9795 - accuracy: 0.4833
Epoch 9/150
38/38 [==============================] - 0s 3ms/step - loss: 1.0414 - accuracy: 0.5133
Epoch 10/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9897 - accuracy: 0.4633
Epoch 11/

# <신체 + model_1&5 예측값 -> model_6(id_3 수치)로 예측>

In [28]:
#예측값 붙여주기
#X_model_6 = X_onlybody+model_1 & 5_prediction
predict_model_5_list=np.array(predict_model_5_list, dtype='float64')
predict_model_5_list=predict_model_5_list.reshape(-1,1)
X_model_6=np.hstack([X_onlybody, predict_model_1_list, predict_model_5_list])

#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_model_6,Y_model_3,train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_6 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_6.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_6.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_6.save('DNN_LDL_4categorical(model_6)_forprediction_TG.h5')

accuracy_list[5]=round((model_6.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_6=model_6.predict(X_model_6)

predict_model_6_list=[]
for li in predict_model_6:
    index=li.argmax()
    predict_model_6_list.append(index)

for i in range(4):
    class_list[5][i]=predict_model_6_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 5ms/step - loss: 3.7994 - accuracy: 0.6200
Epoch 2/150
38/38 [==============================] - 0s 4ms/step - loss: 2.0634 - accuracy: 0.6667
Epoch 3/150
38/38 [==============================] - 0s 3ms/step - loss: 1.5094 - accuracy: 0.6633
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.2733 - accuracy: 0.6567
Epoch 5/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9466 - accuracy: 0.7300
Epoch 6/150
38/38 [==============================] - 0s 3ms/step - loss: 0.9674 - accuracy: 0.7367
Epoch 7/150
38/38 [==============================] - 0s 3ms/step - loss: 0.8627 - accuracy: 0.7333
Epoch 8/150
38/38 [==============================] - 0s 3ms/step - loss: 0.8241 - accuracy: 0.7567
Epoch 9/150
38/38 [==============================] - 0s 3ms/step - loss: 0.8116 - accuracy: 0.7767
Epoch 10/150
38/38 [==============================] - 0s 3ms/step - loss: 0.7168 - accuracy: 0.7867
Epoch 11/

In [9]:
#예측값 붙여주기
#X_model_6 = X_onlybody+model_1 & 5_prediction
predict_model_5_list=np.array(predict_model_5_list, dtype='float64')
predict_model_5_list=predict_model_5_list.reshape(-1,1)
X_model_6=np.hstack([X_onlybody, predict_model_1_list, predict_model_5_list])

predict_model_6=model_6.predict(X_model_6)

predict_model_6_list=[]
for li in predict_model_6:
    index=li.argmax()
    predict_model_6_list.append(index)

print(predict_model_6)
print(predict_model_6_list)

1/1 [==============================] - 0s 151ms/step
[[6.9756648e-03 9.9301839e-01 5.7972170e-06 2.1664528e-07]]
[1]


# <신체 + model_1&5&6 예측값 -> model_7(id_4 수치)로 예측>

In [31]:
#예측값 붙여주기
#X_model_7 = X_onlybody+model_1 & 5 & 6_prediction
predict_model_6_list=np.array(predict_model_6_list, dtype='float64')
predict_model_6_list=predict_model_6_list.reshape(-1,1)
X_model_7=np.hstack([X_onlybody, predict_model_1_list, predict_model_5_list, predict_model_6_list])


#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_model_7,Y_model_4,train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_7 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_7.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_7.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_7.save('DNN_LDL_4categorical(model_7)_forprediction_TC.h5')

accuracy_list[6]=round((model_7.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_7=model_7.predict(X_model_7)

predict_model_7_list=[]
for li in predict_model_7:
    index=li.argmax()
    predict_model_7_list.append(index)

for i in range(4):
    class_list[6][i]=predict_model_7_list.count(i)

Epoch 1/150
38/38 [==============================] - 1s 3ms/step - loss: 5.0191 - accuracy: 0.4900
Epoch 2/150
38/38 [==============================] - 0s 3ms/step - loss: 2.5267 - accuracy: 0.4533
Epoch 3/150
38/38 [==============================] - 0s 3ms/step - loss: 1.7209 - accuracy: 0.4600
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.3699 - accuracy: 0.4967
Epoch 5/150
38/38 [==============================] - 0s 3ms/step - loss: 1.3656 - accuracy: 0.4400
Epoch 6/150
38/38 [==============================] - 0s 4ms/step - loss: 1.2377 - accuracy: 0.4733
Epoch 7/150
38/38 [==============================] - 0s 3ms/step - loss: 1.1886 - accuracy: 0.4633
Epoch 8/150
38/38 [==============================] - 0s 3ms/step - loss: 1.0315 - accuracy: 0.5467
Epoch 9/150
38/38 [==============================] - 0s 5ms/step - loss: 1.0876 - accuracy: 0.5300
Epoch 10/150
38/38 [==============================] - 0s 5ms/step - loss: 1.0298 - accuracy: 0.5300
Epoch 11/

In [32]:
#예측값 붙여주기
#X_model_7 = X_onlybody+model_1 & 5 & 6_prediction
predict_model_6_list=np.array(predict_model_6_list, dtype='float64')
predict_model_6_list=predict_model_6_list.reshape(-1,1)
X_model_7=np.hstack([X_onlybody, predict_model_1_list, predict_model_5_list, predict_model_6_list])

predict_model_7=model_7.predict(X_model_7)

predict_model_7_list=[]
for li in predict_model_7:
    index=li.argmax()
    predict_model_7_list.append(index)
    
print(predict_model_7)
print(predict_model_7_list)

 1/12 [=>............................] - ETA: 0s

12/12 [==============================] - 0s 2ms/step
[[0.5460953  0.2899815  0.1639232 ]
 [0.529128   0.29687148 0.17400044]
 [0.5212012  0.30612215 0.17267671]
 ...
 [0.51144654 0.3028327  0.1857208 ]
 [0.51349187 0.29405499 0.19245315]
 [0.58158845 0.29650646 0.12190507]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

# <신체 + model_5&6&7 예측값 -> model_8(id_1 수치)로 예측>

In [35]:
#예측값 붙여주기
#X_model_8 = X_onlybody+model_5 & 6 & 7_prediction
predict_model_7_list=np.array(predict_model_7_list, dtype='float64')
predict_model_7_list=predict_model_7_list.reshape(-1,1)
X_model_8=np.hstack([X_onlybody, predict_model_5_list, predict_model_6_list, predict_model_7_list])


#train-test 데이터 생성
x_train,x_test,y_train,y_test=train_test_split(X_model_8,Y_model_1,train_size=0.8, random_state=100)

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_test_encoded = tf.keras.utils.to_categorical(y_test)

model_8 = tf.keras.models.Sequential([
        tf.keras.layers.Dense(units=128, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax')
    ])
model_8.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_8.fit(x_train, y_train_encoded, epochs=150, batch_size=8, use_multiprocessing=True)

model_8.save('DNN_LDL_4categorical(model_8)_forprediction_LDL.h5')

accuracy_list[7]=round((model_8.evaluate(x_test, y_test_encoded)[1]*100),2)

predict_model_8=model_8.predict(X_model_8)

predict_model_8_list=[]
for li in predict_model_8:
    index=li.argmax()
    predict_model_8_list.append(index)

for i in range(4):
    class_list[7][i]=predict_model_8_list.count(i)

Epoch 1/150
38/38 [==============================] - 2s 4ms/step - loss: 5.0492 - accuracy: 0.4233
Epoch 2/150
38/38 [==============================] - 0s 4ms/step - loss: 2.4427 - accuracy: 0.4900
Epoch 3/150
38/38 [==============================] - 0s 4ms/step - loss: 1.6631 - accuracy: 0.4333
Epoch 4/150
38/38 [==============================] - 0s 3ms/step - loss: 1.4770 - accuracy: 0.4933
Epoch 5/150
38/38 [==============================] - 0s 3ms/step - loss: 1.2684 - accuracy: 0.5200
Epoch 6/150
38/38 [==============================] - 0s 3ms/step - loss: 1.1566 - accuracy: 0.4933
Epoch 7/150
38/38 [==============================] - 0s 3ms/step - loss: 1.1207 - accuracy: 0.4933
Epoch 8/150
38/38 [==============================] - 0s 3ms/step - loss: 1.0526 - accuracy: 0.4933
Epoch 9/150
38/38 [==============================] - 0s 4ms/step - loss: 1.0498 - accuracy: 0.5100
Epoch 10/150
38/38 [==============================] - 0s 4ms/step - loss: 1.0247 - accuracy: 0.4800
Epoch 11/

In [14]:
#예측값 붙여주기
#X_model_8 = X_onlybody+model_5 & 6 & 7_prediction
predict_model_7_list=np.array(predict_model_7_list, dtype='float64')
predict_model_7_list=predict_model_7_list.reshape(-1,1)
X_model_8=np.hstack([X_onlybody, predict_model_5_list, predict_model_6_list, predict_model_7_list])

predict_model_8=model_8.predict(X_model_8)

predict_model_8_list=[]
for li in predict_model_8:
    index=li.argmax()
    predict_model_8_list.append(index)

print(predict_model_8)
print(predict_model_8_list)

1/1 [==============================] - 0s 98ms/step
[[1.27293774e-11 3.13148284e-14 4.09564151e-08 1.00000000e+00]]
[3]


## <결과 출력>

In [37]:
# 정확도 출력
for i in range(8):
    print(f"model {i+1} accuracy: {accuracy_list[i]}%")

model 1 accuracy: 62.67%
model 2 accuracy: 60.0%
model 3 accuracy: 77.33%
model 4 accuracy: 49.33%
model 5 accuracy: 64.0%
model 6 accuracy: 77.33%
model 7 accuracy: 49.33%
model 8 accuracy: 60.0%
